-- Sample Business Data for Iraq Business Directory
-- Arabic, Kurdish, and English businesses

INSERT INTO businesses (id, name, name_normalized, language, category, governorate, city, phone, whatsapp, email, website, facebook, instagram, bio, description, latitude, longitude, tags, status, created_at) VALUES
('biz_001', 'مطعم الشرقية', 'مطعمالشرقية', 'ar', 'Restaurants & Cafes', 'Baghdad', 'Baghdad', '+9647701234567', '+9647701234567', 'restaurant@iraq.iq', 'https://www.alsharqiya.iq', 'https://fb.com/alsharqiya', 'https://instagram.com/alsharqiya', 'مطعم عراقي أصيل يقدم أشهى المأكولات الشعبية والمشاوي. نفتح يومياً من الساعة 10 صباحاً حتى منتصف الليل.', 'مطعم الشرقية هو مطعم عراقي تقليدي يقدم أشهى الأطباق العراقية الأصيلة مثل الكباب والبرياني والدولمة. يتميز المطعم بأجواء عائلية مريحة وخدمة ممتازة.', 33.3128, 44.3615, 'iraqi,food,family', 'active', datetime('now')),

('biz_002', 'كافيه العراق', 'كافيهالعراق', 'ar', 'Restaurants & Cafes', 'Baghdad', 'Baghdad', '+9647801234567', '+9647801234567', 'cafe@iraq.iq', 'https://www.cafeiraq.iq', 'https://fb.com/cafeiraq', 'https://instagram.com/cafeiraq', 'كافيه عصري في قلب المدينة يقدم القهوة المختصة والمشروبات الباردة. أجواء هادئة ومريحة للعائلات.', 'كافيه العراق هو كافيه عصري يقع في قلب بغداد، يقدم القهوة المختصة والمشروبات الباردة والحلويات. يتميز بأجواء هادئة ومريحة مناسبة للعائلات.', 33.3150, 44.3650, 'coffee,modern,relax', 'active', datetime('now')),

('biz_003', 'صيدلية الشفاء', 'صيدليةالشفاء', 'ar', 'Health & Medical Services', 'Basra', 'Basra', '+9647901234567', '+9647901234567', 'pharmacy@iraq.iq', 'https://www.alshifa.iq', 'https://fb.com/alshifa', 'https://instagram.com/alshifa', 'صيدلية متكاملة توفر جميع الأدوية والمستلزمات الطبية. خدمة على مدار الساعة وتوصيل للمنازل.', 'صيدلية الشفاء هي صيدلية متكاملة توفر جميع الأدوية والمستلزمات الطبية والمنتجات الصحية. تقدم خدمة على مدار الساعة مع خدمة توصيل للمنازل.', 30.5433, 47.7979, 'pharmacy,health,delivery', 'active', datetime('now')),

('biz_004', 'مكتب العقارات الذهبي', 'مكتبالعقاراتالذهبي', 'ar', 'Real Estate', 'Erbil', 'Erbil', '+9647501234567', '+9647501234567', 'golden@iraq.iq', 'https://www.goldenrealestate.iq', 'https://fb.com/goldenrealestate', 'https://instagram.com/goldenrealestate', 'متخصصون في بيع وتأجير العقارات السكنية والتجارية في جميع أنحاء العراق. خبرة أكثر من 15 عاما.', 'مكتب العقارات الذهبي هو مكتب عقارات متخصص في بيع وتأجير العقارات السكنية والتجارية في جميع أنحاء العراق. يتميز بخبرة أكثر من 15 عاماً في السوق العراقي.', 36.1912, 44.0091, 'real,estate,property', 'active', datetime('now')),

('biz_005', 'محل الإلكترونيات الحديث', 'محلالإلكترونياتالحديث', 'ar', 'Electronics & Tech Shops', 'Nineveh', 'Mosul', '+9647601234567', '+9647601234567', 'electronics@iraq.iq', 'https://www.modernelectronics.iq', 'https://fb.com/modernelectronics', 'https://instagram.com/modernelectronics', 'أحدث الأجهزة الإلكترونية والهواتف الذكية بأسعار تنافسية. ضمان سنة وخدمة ما بعد البيع.', 'محل الإلكترونيات الحديث يقدم أحدث الأجهزة الإلكترونية والهواتف الذكية واللابتوبات بأسعار تنافسية. يوفر ضمان سنة على جميع المنتجات مع خدمة ما بعد البيع.', 36.3539, 43.1581, 'electronics,phones,tech', 'active', datetime('now')),

('biz_006', 'خواردنگەی سەرکەوتن', 'خواردنگەیسەرکەوتن', 'ku', 'Restaurants & Cafes', 'Sulaymaniyah', 'Sulaymaniyah', '+9647701234568', '+9647701234568', 'sarkawet@iraq.iq', 'https://www.sarkawet.iq', 'https://fb.com/sarkawet', 'https://instagram.com/sarkawet', 'چێشتخانەیەکی کوردی ئەسیل کە خواردنی دەستپێکردن و کەبابی دەپێشکەش دەکات. ڕۆژانە لە کاتژمێر ١٠ی بەیانی تا نیوەشەو کراوەیە.', 'خواردنگەی سەرکەوتن چێشتخانەیەکی کوردی ئەسیلە کە خواردنی دەستپێکردن و کەبابی دەپێشکەش دەکات. ڕۆژانە لە کاتژمێر ١٠ی بەیانی تا نیوەشەو کراوەیە.', 35.5607, 46.4384, 'kurdish,food,traditional', 'active', datetime('now')),

('biz_007', 'دەرمانخانەی ژیان', 'دەرمانخانەیژیان', 'ku', 'Health & Medical Services', 'Erbil', 'Erbil', '+9647801234568', '+9647801234568', 'zhian@iraq.iq', 'https://www.zhian.iq', 'https://fb.com/zhian', 'https://instagram.com/zhian', 'دەرمانخانەیەکی تەواو کە هەموو دەرمان و پێداویستییەکانی پزیشکی دەپێشکەش دەکات. خزمەتگوزاری ٢٤ کاتژمێر.', 'دەرمانخانەی ژیان دەرمانخانەیەکی تەواوە کە هەموو دەرمان و پێداویستییەکانی پزیشکی دەپێشکەش دەکات. خزمەتگوزاری ٢٤ کاتژمێر.', 36.1912, 44.0091, 'pharmacy,kurdish,health', 'active', datetime('now')),

('biz_008', 'Al-Rasheed Restaurant', 'alrasheedrestaurant', 'en', 'Restaurants & Cafes', 'Baghdad', 'Baghdad', '+9647701234569', '+9647701234569', 'alrasheed@iraq.iq', 'https://www.alrasheed.iq', 'https://fb.com/alrasheed', 'https://instagram.com/alrasheed', 'Authentic Iraqi cuisine serving traditional dishes and grilled meats since 1995. Open daily, family-friendly atmosphere.', 'Al-Rasheed Restaurant has been serving authentic Iraqi cuisine since 1995. We offer traditional dishes like kebab, biryani, and dolma in a family-friendly atmosphere.', 33.3128, 44.3615, 'iraqi,food,traditional', 'active', datetime('now')),

('biz_009', 'Baghdad Tech Hub', 'baghdadtechhub', 'en', 'IT & Software Services', 'Baghdad', 'Baghdad', '+9647801234569', '+9647801234569', 'tech@iraq.iq', 'https://www.baghdadtech.iq', 'https://fb.com/baghdadtech', 'https://instagram.com/baghdadtech', 'Full-service IT solutions provider offering web development, networking, and software support. Serving businesses across Iraq.', 'Baghdad Tech Hub is a full-service IT solutions provider offering web development, networking, and software support. We serve businesses across Iraq with expert teams.', 33.3150, 44.3650, 'it,software,tech', 'active', datetime('now')),

('biz_010', 'Tigris Pharmacy', 'tigrispharmacy', 'en', 'Health & Medical Services', 'Nineveh', 'Mosul', '+9647901234569', '+9647901234569', 'tigris@iraq.iq', 'https://www.tigris.iq', 'https://fb.com/tigris', 'https://instagram.com/tigris', 'Fully stocked pharmacy offering prescription and over-the-counter medications. Delivery available and open 24 hours for emergencies.', 'Tigris Pharmacy is fully stocked with prescription and over-the-counter medications. We offer delivery service and are open 24 hours for emergencies.', 36.3539, 43.1581, 'pharmacy,health,delivery', 'active', datetime('now'));
